/*
 * generated by Xtext 2.16.0
 */
package io.typefox.examples.theia.states.tests

import com.google.inject.Inject
import io.typefox.examples.theia.states.states.ProcessDefinition
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(StatesInjectorProvider)
class StatesParsingTest {
	@Inject
	ParseHelper<ProcessDefinition> parseHelper

	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			process p1

			start start1
			activity activity1
			end end1

			edge start1 => activity1
			edge activity1 => end1
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
